title: Site
pages:
  template:
    - home
    - quizes
    - members
    - hosts
    - names
files: true
fields:
  title:
    label: Site Name

  section_seo:
    label: SEO
    type: headline

  keywords:
    label: Keywords
    type: tags
  description:
    label: Description
    type: textarea
    buttons: false
    help: >
      To be used in the description Meta tag. Keep this short, preferably under 160 characters.


